---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routing-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: routing
    project: gateway
spec:
  project: gateway
  source:
    repoURL: "https://github.com/edenreich/infrastructure"
    targetRevision: main
    path: gateway
  destination:
    name: gateway
    namespace: main
  syncPolicy:
    automated:
      prune: true
      # selfHeal: true
    syncOptions:
      - CreateNamespace=true
