---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routing-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: routing
    app.kubernetes.io/part-of: routing
spec:
  project: gateway
  source:
    repoURL: https://github.com/edenreich/infrastructure.git
    targetRevision: main
    path: routing
  destination:
    name: gateway
    namespace: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
