---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/part-of: routing
spec:
  project: gateway
  source:
    repoURL: https://github.com/kubernetes-sigs/external-dns.git
    path: charts/external-dns
    targetRevision: v0.13.1
    helm:
      releaseName: external-dns
      values: |
        provider: cloudflare
        txtPrefix: "managed-by-external-dns-"
        sources:
          - ingress
          - crd
        triggerLoopOnEvent: true
        policy: sync
        extraArgs:
        - --zone-id-filter=41fb639d751b412ad8f699e5d498004f
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare
              key: cf_api_token
  destination:
    name: gateway
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-crds-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/part-of: routing
spec:
  project: gateway
  source:
    repoURL: https://github.com/kubernetes-sigs/external-dns.git
    path: docs/contributing/crd-source
    targetRevision: v0.13.1
  destination:
    name: gateway
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
