---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visualisation
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: visualisation
    app.kubernetes.io/part-of: observability
spec:
  project: gateway
  source:
    repoURL: https://github.com/edenreich/infrastructure.git
    targetRevision: main
    path: observability/visualisation
  destination:
    name: gateway
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
