---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-staging
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: cluster
    project: staging
spec:
  project: staging
  source:
    repoURL: 'https://github.com/edenreich/infrastructure'
    targetRevision: master
    path: clusters/bullseye-64bit/control-plane.yaml
  destination:
    name: staging
    namespace: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
