---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubernetes-upgrades
  namespace: argocd
  labels:
    app.kubernetes.io/name: kubernetes-upgrades
    app.kubernetes.io/part-of: system-upgrades
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            project: build
          - cluster: staging
            project: staging
          - cluster: production
            project: production
          - cluster: gateway
            project: gateway
  template:
    metadata:
      name: "kubernetes-upgrades-{{project}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        app.kubernetes.io/name: kubernetes-upgrades
        app.kubernetes.io/part-of: system-upgrades
    spec:
      project: "{{project}}"
      source:
        repoURL: https://github.com/rancher/system-upgrade-controller.git
        targetRevision: HEAD
        path: manifests
      destination:
        name: "{{cluster}}"
        namespace: system-upgrade
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true
