---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: certificates-management
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            project: build
          - cluster: staging
            project: staging
          - cluster: production
            project: production
          - cluster: gateway
            project: gateway
  template:
    metadata:
      name: "cert-manager-{{project}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/part-of: certificates-management
    spec:
      project: "{{project}}"
      source:
        chart: cert-manager
        repoURL: https://charts.jetstack.io
        targetRevision: v1.9.1
        helm:
          releaseName: cert-manager
          values: |
            installCRDs: true
      destination:
        name: "{{cluster}}"
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
