---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-ingress
  namespace: argocd
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/part-of: routing
spec:
  generators:
    - list:
        elements:
          - cluster: staging
            project: staging
          - cluster: production
            project: production
          - cluster: gateway
            project: gateway
  template:
    metadata:
      name: "nginx-ingress-{{project}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        app.kubernetes.io/name: nginx-ingress
        app.kubernetes.io/part-of: routing
    spec:
      project: "{{project}}"
      source:
        chart: nginx-ingress
        repoURL: https://helm.nginx.com/stable
        targetRevision: 0.13.2
        helm:
          releaseName: nginx-ingress
          parameters:
            - name: controller.replicaCount
              value: "2"
      destination:
        name: "{{cluster}}"
        namespace: nginx-ingress
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
