---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/part-of: encryption-management
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            project: build
          - cluster: staging
            project: staging
          - cluster: production
            project: production
          - cluster: gateway
            project: gateway
  template:
    metadata:
      name: "sealed-secrets-{{project}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        app.kubernetes.io/name: sealed-secrets
        app.kubernetes.io/part-of: encryption-management
    spec:
      project: "{{project}}"
      source:
        repoURL: https://github.com/bitnami-labs/sealed-secrets.git
        path: helm/sealed-secrets
        targetRevision: v0.22.0
        helm:
          releaseName: sealed-secrets
          parameters:
            - name: keyrenewperiod
              value: "0"
      destination:
        name: "{{cluster}}"
        namespace: sealed-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
