---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: production
    project: infrastructure
spec:
  project: infrastructure
  source:
    repoURL: "https://github.com/edenreich/infrastructure.git"
    path: argocd/01-clusters/production
    targetRevision: main
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
