apiVersion: v1
kind: Service
metadata:
  name: staging-cluster
  namespace: main
spec:
  type: ExternalName
  externalName: k8s-staging-server.local
  ports:
  - name: http
    port: 8080
    targetPort: 80
