apiVersion: v1
kind: Service
metadata:
  name: production-cluster
  namespace: main
spec:
  type: ExternalName
  externalName: production.local
  ports:
  - name: http
    port: 8080
    targetPort: 80
