apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: external-dns
spec:
  encryptedData:
    cf_api_email: AgDUFANYT2+8ZgTIZDHMQVzGoE7/6W0e06vuL32b/Y5nUCgmD9srv+ocM/BrqetizFaG7ihu4K2Sp1wrQey2qVKvg9Mt1Gw9ff40v/hoblpgPjmYihT6oCz86XKsGC36wXwpi5d1apXqwTJmWrHcs6PUgDD6OwDazB+hy0mUDI5gfrxtvUie5pVJj1G7JxB9fnO7W8mH2MRIOM+GlqEchTfFPcLgTOrqi+jkS0JFpCxOFut11ISoU8KfxLnBG29IHc7KalTvgGgfaKJ63TJ+4mAi9X/s3xwWG/RvPRONRmI4JBX2AY1sQ1zNRaYfqE3Jfxg4JZrcwng6n68QIeiKJc2dycfxDZO3PW6igLtjdG3wRmKxj2+qV1s+vWoLEUvLDO4VdpImKct/L0D6T/NNumbA58YE7P2x3kvEU2tGmkD9/SboqCqdpUG+JXUa/CVRzS5oNrnyi+JF2GBSMJewfYvifl4O2NzkspWHJkni3OAjdkBSsK/C2zcKFSZyvejc3bieRWACPhzf1Pb7pWDuhjbUN7XQSXesUtsOviabKqdysRWI+3/AKe+eszyqTFbLyWEBvyATm6Fp41tR0Bgi1OgNq2EfZUoetnRSIlxUoiGBcMypViJYIdUco0z9OgPrxeZg/fj1gzAzFZnVnXBqk22wuvBFo/sgH0HBHH5n2Pps9B8r2OGh7Kj1/KEbKobEJYLf1sKefuAOsmeJbONARTUk9Tk83fI=
    cf_api_key: AgBY5TvigZg/kfuy3YcRKXT/00Vp2uhWHxy/TXZPvBPA/8EzdwL81yOqa+ZY0dwSUZfVimTE0mhALmrCq0i6gQHDLE7nDsiVMlrmaXJuxDD0+PKlAIw9fP1tTEvc6n2O3SWqoVeeCRcsTMyHl+ELjAuwLtxJF654IyvR1aYXlHUybbC+s3YA8wsm3DU0SUWXfmCUoicYb0iliKfZU6psVhXfqdk9sQ0KxKM64WzUn8SrP4lQOmEueJUoEeaYEAxWuFsEq9pBuXfiadniMflEI5xUKSgTMAFXxwnZbd9SqtzKLSD3U7TpfZXzgf6gGKdMmwBortiFaAhdWSVFtlrPr2uvKCE36uLK7WJp7C8dKuynnXr24sin3+z7f/+esk7cJLvpwDpoRzpo+4kytobFfpFT0MDaFJZ4gvGhRVXtoXvS7hGAkgkl+Ss6Hx1Wf3hXSS28YVRN/8MWPxaMCsfgbPcvR6WJjT1AXvA8RD/Kn92SPkzv51MOds1/0Jzpflf3FDAWYu0pIG/dppFvf4Bs4yqVsdO8sVm6cm4fxFfNjmJQnZmxQOw45FFWLRmMuYv+izrTxZwH/V9T61MJP/lFVNXgueM31UDSD0tdUPI2/OVBntCbCxhkB4IZFAtMmu1U1hNkm1KHfLuntERTZx8tcSFGxEuyonJ8AxOAMPQi1s82C9oRzioYsAPJ23A0xiTMxgnuc/v9gkAx3jjvIXHB5H7YlXKNeSU2t5RxjXvTVwxmRUFKKdAZ7jWGfQ==
  template:
    metadata:
      name: cloudflare
      namespace: external-dns
    type: Opaque
