apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: external-dns
spec:
  encryptedData:
    cf_api_token: AgDJaAuoviP5h+4K2Yu5YisO5lMtUojB0mqF1R481JY8Wpg+sNGX+JqFSOyztFWHL2yrIdam1b9maH3ijMrT7H9By5oWL2dIXyhZQZz4bYvlkot4TG885zAUjb9kAYx9+OUMFwno7YSBfm8Vg+DvCD7hCReVcKa6MNHlgs2Lkimon78WgZTw9t9Ead3lDkSnfgxbJVym2E17f5wSKVtBKqVGO2yI8QVDtJutytjHvkCUdHQOupZ4cRTN4+FMXgqIXfufF1z0UrXq2aFfjbtJ5t8GcoqxnRUr6vciWdXBz6mgzWkvhvYqjV3SnEGpm148hr+gYad9qHgVbOEAsLWWEs8HyiYKAWb5R3tpuQEmftE/fAXGqlmneY5aQjwF0xSgerdKHudARoBqMnrHsAwYMEzu4cxOu9tEL0dgKC+p5edbn9SWhc/zdIqiqV/JzQbsq8jfZstE2s83cFHP5E4BU+MyEIquVmotRp4yrV1Flov3q55R3PE0YgbI4H5I2vZ1et1eWCOmHsByFM+CmnMU7LFP9S3+jAiayys4jBgQYI/eJGjwaLqpjfBJI3Hes8NKDYO5hx0Z2oPVa7STibJqeXMjqwYdbT5sAw4AEWp5jik77hsJ9p0nerflIa6zXjIquQHxl6IRyR2O463sLf2jLLeUqtRyxDHVXwqGmr6jdoH/1PiiSdAXt4NU/PBXbjxqBDVu5anq42T0J9jZe9UbTFjfnjlDXLYFCvdaOUgZzCuobXiJ9TcbaFGN6Q==
  template:
    data: null
    metadata:
      name: cloudflare
      namespace: external-dns
    type: Opaque
