---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: external-dns
spec:
  encryptedData:
    cf_api_token: AgCOqWwriyXBV6dW25l2C7IibKouxFkOWP536+58iBgC/30va9Sgxaz3JC80/0sFkBPwWd2ByKydBwe1C568hMrk3FDGerEnL4FXSlNz7ysig8zjERMLmfqEIZU+DFXBTPS8rvjsWUWWy3PIc9lucjyp4uZMH+3XrTnEcJFkYuOxofMAl4b4urLKo9pVETWo8e78G90EHH36yssy9paJ122XeEciia8rUTTOdJRS8p6FwuNp+cGZKORueqvMSSiSDgJUCp/QzmAdoJiRExr6Pb/7NW5XrzgczRY4NuEPnonEAY1cb4Lfor2QP1L7ylruGPgAFxWJfdbiPnzcHJj2J4PJyUUhfO5W1gIm1rCpugvBfxc1gjrpFRSNTG6EYKzuF01qj74BZwFubYRIcw6dQqWjciPR18/mjhZSDUbQ9LmGoMQq52NQghYnuK0FUGcRFJLe6QDyX7iFBVbyHpA3FBWeZadNQktiiqbWfWdJii5wuU8dZ4gy19sPsscfTch1otm2x+ACub93V59FDysV5tf8BKe3mA3tJV6OcWNYV0mj+71GzkCj9KtwiospYqpRZGwRXsO+UehYu7Z0ZUOPy7l27voFpDmXiaAhJc7jhWgbW+kwR9OkyksEkzp2lGi0sbUPlxo6X6EPdCP9TR8Grn8K7KrxurS/xVDjoDyu7+EPszOXpeBZBlAKmOKm9l+RTE+pPSpXcpIZImF2sFGuRmnZr6XoslwPQnzwSvgx5KRK5zCgj+iqIr02
  template:
    metadata:
      name: cloudflare
      namespace: external-dns
    type: Opaque
