apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: external-dns
spec:
  encryptedData:
    cf_api_token: AgAlgTBSTT6OMGB5X5yXPF7d+8ue5XZfh1Uomou74yVKoy6zAPYDpR2kY5Wo39wEAyZE2kbghn5bcYIl5I+RQ7EDzYGZ9xp/nPed81sPwMXk1dpko/yVH77jPbBJnRXOw0nCnrexwVg3nNocMBxoWhx9H8AYfi4x9+ZD7vktHI2jlUgCnyDVJZ58Ztsf7W637vjzGAWaSyf+2Drqeqm0rbuNVZ5UIIc/EwcLvMUxiAtkYPiUuvl2RRN13LRNSFFY7h750OZ8bfb9gG2S4ORdRAVkw4gHGmfd/x/u5xq4EQHbHptYkcAXsmNAcj9JCPpQDrjKzVF7RiY5vfw47vZqy7mJ5INKN0cDpPEU2UKL2WnM+RKkfCe0GkXhFuQxFGAk1Ye9kojzj2WJCsK17P6o9NJsKD6lDWZhs6agUH1Iq4BVdFtmpRs/UI+Uq6v2XAf8/d86lknMpoV3Rl3DZ7hc+VYxoHHhjOK5fu3cbEfZmx2Zt5qPldA3OzWLwN5swO0+Ez/e/vwoze0TQOiRCr4UJ4M7lly8JUGz9+Ahie6YAya4j1MMfz+bz4ooGzCvbaE5J9FRHyhTbWV61NlgNh9E31Qqb/zWmDFHSzZtM3BQvKh6KKJUPhs5Kr6vxYBpIdJGXyg5Hwj+lL8J/So01Lom1RIdfQr/eiXVYBsjKnozbgZniIsPX1FVb5Cf7GB2M+awUnydoWozva2H26Dw/fRFnhbSPV7s6eO4IsgzTjPpTXt/AeKRaxncOcL14A==
  template:
    data: null
    metadata:
      name: cloudflare
      namespace: external-dns
    type: Opaque
