---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: observability
spec:
  config:
    log:
      mode: console
    auth:
      disable_login_form: "false"
    security:
      admin_user: admin
      admin_password: secret
  datasources:
    - name: jaeger
      type: jaeger
      access: proxy
      url: http://jaeger-query:16686
      jsonData:
        traceNameLimit: 80
        tags:
          regex: ""
          exclude: false
