---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: otel
  namespace: observability
  labels:
    app.kubernetes.io/name: otel
    app.kubernetes.io/part-of: observability
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: prometheus
    type: prometheus
    url: http://otel-collector-collector-monitoring:8888
