---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: otel
  namespace: observability
  labels:
    app.kubernetes.io/name: otel
    app.kubernetes.io/part-of: observability
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  datasource:
    name: OpenTelemetry
    type: prometheus
    url: http://otel-collector-collector-monitoring:8888
    access: proxy
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      incrementalQuerying: true
      incrementalQueryOverlapWindow: 10m
      cacheLevel: 'High'
    editable: true
