---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gateway
  source:
    repoURL: 'https://github.com/edenreich/infrastructure'
    targetRevision: master
    path: gateway
  destination:
    name: gateway
    namespace: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
