---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argocd
  labels:
    name: sealed-secrets
spec:
  generators:
  - list:
      elements:
      # - cluster: staging
      #   project: staging
      # - cluster: production
      #   project: production
      - cluster: in-cluster
        project: build
      - cluster: gateway
        project: gateway
  template:
    metadata:
      name: 'sealed-secrets-{{project}}'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      labels:
        name: sealed-secrets
        project: '{{project}}'
    spec:
      project: '{{project}}'
      source:
        chart: sealed-secrets
        repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
        targetRevision: 2.3.0
        helm:
          releaseName: sealed-secrets
      destination:
        name: '{{cluster}}'
        namespace: sealed-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
