---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    chart: sealed-secrets
    repoURL: "https://bitnami-labs.github.io/sealed-secrets"
    targetRevision: 2.3.0
    helm:
      releaseName: sealed-secrets
  destination:
    name: staging
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
