---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    chart: metrics-server
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 6.0.8
    helm:
      releaseName: metrics-server
      values: |
        apiService:
          create: true
        extraArgs:
          - --kubelet-insecure-tls=true
          - --kubelet-preferred-address-types=InternalIP
        pdb:
          create: true 
          minAvailable: "1"
          maxUnavailable: ""
  destination:
    name: staging
    namespace: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
