---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: gateway
    app.kubernetes.io/app-of-apps: "true"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/edenreich/infrastructure.git
    targetRevision: main
    path: argocd/01-clusters/gateway
  destination:
    name: in-cluster
    namespace: argocd
