---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gateway
  source:
    chart: cert-manager
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.8.2
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
  destination:
    name: gateway
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
