---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: engineering-blog-production
  namespace: main
  labels:
    name: production
spec:
  endpoints:
    - dnsName: eden-reich.com
      recordTTL: 120
      recordType: AAAA
      targets:
        - 2606:50c0:8000::153
        - 2606:50c0:8001::153
        - 2606:50c0:8002::153
        - 2606:50c0:8003::153
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'true'
    - dnsName: www.eden-reich.com
      recordTTL: 120
      recordType: CNAME
      targets:
        - eden-reich.com
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'true'
    - dnsName: engineering-blog.eden-reich.com
      recordTTL: 120
      recordType: CNAME
      targets:
        - eden-reich.com
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'true'
