---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: engineering-blog-production
  namespace: main
  labels:
    name: production
spec:
  endpoints:
    - dnsName: engineering-blog.eden-reich.com
      recordTTL: 120
      recordType: A
      targets:
        - 185.199.108.153
        - 185.199.109.153
        - 185.199.110.153
        - 185.199.111.153
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'true'
    - dnsName: www.eden-reich.com
      recordTTL: 120
      recordType: CNAME
      targets:
        - engineering-blog.eden-reich.com
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'true'
