---
- name: Cleanup K3S resources
  gather_facts: false
  hosts: all
  tasks:
    - name: Remove dangling container images
      become: true
      ansible.builtin.command: k3s crictl rmi --prune
      tags:
        - skip_ansible_lint
