---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: build
  namespace: argocd
  labels:
    name: build
spec:
  description: 'Build project'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
  destinations:
  - name: 'in-cluster'
    namespace: '*'
