---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: staging
spec:
  description: "Staging project"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
  destinations:
    - name: "staging"
      namespace: "*"
