---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gateway
  namespace: argocd
  labels:
    name: gateway
spec:
  description: "Gateway project"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
  destinations:
    - name: "gateway"
      namespace: "*"
