---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: blog
    project: production
spec:
  project: production
  source:
    repoURL: "https://github.com/edenreich/blog-new.git"
    path: k8s/production
    targetRevision: add-preview-apps
  destination:
    name: production
    namespace: blog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
