---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgBjg4EZOUy/Lyoxutpvfh/nbL/0Tu/WJN7cY/il5acflKgKKkEjS3ciYmPwQoOAltqbv9+r+j1o0xF4InVfSNYWleQCuy3d8u6exSvrHl8v9n2g+C1x8Ho8Xm0z3ncF5sju2L0shx0BcFHkxCOBlvBkRB0PTxgjUyjTF13rSGUfmcxVDsUw/Yhfo9sKRka988QxwKLLKSPYelQocp809NNaxTNqBKomhzZblINtVo+WyboTcTbTv7P1MgjQXwYu1C0sDCDv6HvOr9xhOwIghdsOU48yLDr+864Xkb/gi2ke/e7JkBNJm4easFVeWIzjXKaovq7RqrRwLjpwNQJkKWZ5cvCSxyhWqX7AbyT2AKYom6g9PbdluhuCwKsCNe3lyMd9mD9Bc1hBNynWo0zrWGpcpiSdt67e80WDyXLZyXR/vke8cl2wIycVwEPu6gVeO++l6xcK6oaP/ARAojns/7itltHgmUVBkJcxyDxT3tEu0D7MVBdEAwOPf508VxzSLWzbbpZTbuF5aDxdTCdKeiDrgNB9vjvQx7Vl0YLlSr0xzt8wpqsmSQvbspfdqPre52yEGxYVMFhonep6x8eSqhIHu4fyg6n4EJ7ys0l5K307SVq5nGl9wd5tflpoJ7VAzffBQw/82a1Z2rmOrUHbghbi0FC+qmkcEPZf8fyN8Ic7dn6qnbveylAmaiicWCo0eXpRdpeMuAzS4UWVBpM8ihiA/I7EUsKVmex+Obh28o2cEnJx5wwxvTzK
  template:
    type: Opaque
    metadata:
      name: controller-manager
      namespace: actions-runner-system
