---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgAzyBAS7TNeUivKUXoVxIzvwZ+vt8GbbzYCSaJVcu+Oxo1ykEa0kM6MX1We9n93ANP0YOxi5uK4AMyyKUED/50m8UlPrYRy+65zkkT4KP1b0NQRCMXeiQsCeY7GkNI2AtGug8Lt5mlXVjjlw4Mg0DwbXrVF6GId3UK2jmeRWFkg4O1iYu4DyGyR7fKaO92dmVCT/JZAkwl1IXR2321BAXfCYIOMynGxw3MDsU5d2vDl9GTBRs7zIiMwK56YfDqO3/96u6bLRbGIonld447bKgbt37hwoU42xXus7YDIC3s4nvk0UNIrWWXFecgniC47jjqhW6HjVqKB5NDNW/wRfaYdwFkkhO0ifbxa01hyV0ssEfe7j6/xzxBmdmgatM9Df+6jtmLUbmA8lrnYN3aBDcZqTi7nWFxi2JMAp6nERNsUbOxkgJUZPpWvuhnNlJPfNsrIz18P3Lbm/s46CJUf1DC0TKHrty901jO95F4OjaJq+xCKqOewrAnodfGo4POFZmrbY6a+KroR+t14M1bPxGwHMSDxBCTqLcOJWUk3p20R4VXduVT2YeYPJ5vshPPIGpcT4QLNOp9D2xhoA8U52Z7NkEiWrZ29kP/wnHNfUTbZW3wmCltZz7ViZvGob+t95LNmb/DgVy6pX5spUzxQsLlfGZuMl96QYRvU0gbBXHOlroYeTLnHG9TdnM8v6ZUycVE3Gl0PZsbvp6LWAM8TR2ZTHIPpYY54mOOeP25iL1My9Tx7od3XeJM+
  template:
    type: Opaque
    metadata:
      name: controller-manager
      namespace: actions-runner-system
