---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflare-build
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: kubeflare
    project: build
spec:
  project: build
  source:
    repoURL: 'https://github.com/edenreich/infrastructure'
    targetRevision: master
    path: cloudflare
  destination:
    name: build
    namespace: kubeflare-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
