---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-gateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: external-dns
    project: gateway
spec:
  project: gateway
  source:
    chart: bitnami/external-dns
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 0.12.2
    helm:
      releaseName: external-dns
      values: |
        cloudflare.secretName: cloudflare
  destination:
    name: gateway
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
