---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-gateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: external-dns
    project: gateway
spec:
  project: gateway
  source:
    repoURL: 'https://github.com/kubernetes-sigs/external-dns.git'
    path: 'charts/external-dns'
    targetRevision: v0.12.2
    helm:
      releaseName: external-dns
      values: |
        provider: cloudflare
        env: ['{name:CF_API_KEY,valueFrom:{secretKeyRef:{name:cloudflare,key:cf_api_key}}}', '{name:CF_API_EMAIL,valueFrom:{secretKeyRef:{name:cloudflare,key:cf_api_email}}}']
  destination:
    name: gateway
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
