---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: build
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: build
    app.kubernetes.io/part-of: build
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/edenreich/infrastructure.git
    targetRevision: main
    path: argocd/01-clusters/build
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
