---
apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-system
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgBUnV0o3+lF/E+sWeI9KwLpYfcw+1Vr+dD0x43skLQBJkfBkGkX/SuB5rsqEm8OgQvOYx5QVaOgREkxJ2fWfH2hS9rtp2P6eODb6ZQau2Z/EDDoQ4PFh4Zh/SpImrg1Wu5xuacp6x5tPncMyt7m+2Z2pmYW7QA8scqJMNjKvoxnY0oJZ53DNdtBNvXHzNVCo6RMw4VGyMUq23ANnlui2zWHF3LeC6DNvDpRE76sEQaDWJRuf7qSqaZO7thLZj0ynP2NvIAFRB+PMhq4/bmM1xTkPxHyBZ2VBRE37GfVoHogEuhJ1pjVNBsvjxpFfSHd5yiF8W5vjynTmBNKiZtfIN4JYSnG9ZlMrML4YI/fBQ96kYgUXwub9RISVGYhZTmXrKxbOitNcezxlrrag22tOVyfDeEmBBp9UZJ6xUiEOl6dzBt40m9FgkUNTJXd+7Q+PDv7UE3INadOgpqTEbaom3BIrGsgNhKzro4zCiEB8wzD+wLYopbbxdlnDmandd14NzZoPxH2wTeKcehNvkMIvekRbaCa1jM04ICUtD5uNi58GS1Jk0wHsFT9+4DMgqu0wMFYHJ6yYBCF/3IAUBJkcLc2MB6Z5GPvYggGV8H8N/dreMgCXdTJV4kKKyxschGjo9n3ibUG390iejABKYnzQrWYS3oINs8phxIpEg+0a2ppcm4cobLqJHMrMp31unJOYeYaCEQSrBV8YTi8tYo7foRPw6BIVP9pJyw8EjzE94QrLM44VT8U7NZu
  template:
    type: Opaque
    metadata:
      name: controller-manager
      namespace: actions-runner-system
