---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    chart: nginx-ingress
    repoURL: 'https://helm.nginx.com/stable'
    targetRevision: 0.13.2
    helm:
      releaseName: nginx-ingress
  destination:
    name: staging
    namespace: nginx-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
