---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: shared
    project: build
spec:
  project: build
  source:
    repoURL: "https://github.com/edenreich/infrastructure"
    targetRevision: master
    path: argocd/01-clusters/shared
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
