---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgABX/e5ZWgxZzYfjR7PtvR0LQvZ5n9l+ErGzef0kS5EXVIryjKKY6aAf+QnUYfsymVEInp207X8rgPfbLO+fOlq9adzdyYcGopmaSxNEtXkTC66c2ExwaASJRNWn7jH4walWmO64z1PzYdkxVNzBkKCe8fprTHUkekcsursI1UWwoLlgxsmjxyexduwapJR8xi1B7+sTAyEeIB3rKe8CBUB8uQcoxi7OisjpuU/B1ZQ27VEmUOgcoSsrCjZ9f8BrmDCtbCTK+xJRrGcI+gvgq1o4BoLcPPqM8IWMOu0BD/6Q/+jg6BDD3dlk48+8hOTgcIVmQkNguEx+WXcfl9Ie17dpZPM1vXOkPkDV3+Dg/0sEN+kXOPfrw8gW1bSmfxjHGxK3C4naVS7SBYXPBtQLC3kU28GHsvs0rQt4bNpyLuUUneKvBCjOovfwRAXfraklFiPTD3TRrni0QLPxNfBq1aeEUi07PosbHPbq43BesUGrb/UTS5qC9eSGRZcXBl4/j+M4/p6DDQ79zHjsVk59AMNdt5dqWJORUDxCUY8oqTOx1Ze19c2ObP85lCcFGgNbz5JZbbObwDV3ladEjMP0Q6Zs9Aqt/oYBU+nxUaI4+3Ge3/OckPUI/6ZgquTbbeyL16JHUkCdesdu6Kt/a3XgUt7wZGPTSqV77HGvJftd79QO2lvucyjPN93iMsyXFiyc3GcM25sB82XUOIgICkZww6B5lgsK683nSU01wW8ORi3UE0axa9zaaBj
  template:
    type: Opaque
    metadata:
      name: controller-manager
      namespace: actions-runner-system
